function Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)
%........................Proiectarea interfetei grafice......................
fig =figure('Name','Roșca David-Sorin: Sumator AO',...
    'Units','normalized',...
    'Position',[0.1 0.1 0.7 0.8],...
    'NumberTitle','off','color',[0.75,0.75,0.75]);
     i=imread('imagine_fundal.jpg');
                image(i);
                set(gca,'Position',[0 0 1 1]);
                axis off; 
 %.............................Rezistențe.............................................................................................................................................................................................................
RadioGroup=uibuttongroup('Visible','on',...
    'BackgroundColor','#A2142F',...
    'Title','Rezistențe:',...
    'FontSize',12,...
    'FontWeight','bold',...
    'TitlePosition','centertop',...
    'FontAngle','italic',...
    'Position',[0.66 0.51 0.2 0.3]); %x, y, l, h

rnT = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.02 0.88 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','Rn',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.88 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
rn = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.4 0.88 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',Rn,...
    'BackgroundColor','w',...
    'Callback',['Rn=','str2num(get(gco,''String''));close; Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
xRnPop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.6 0.88 0.22 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xRn,...
    'BackgroundColor','w',...
    'Callback',['xRn=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
r1T = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.02 0.70 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R1',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.70 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
r1 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.4 0.70 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R1,...
    'BackgroundColor','w',...
    'Callback',['R1=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
xR1Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.6 0.70 0.22 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR1,...
    'BackgroundColor','w',...
    'Callback',['xR1=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
    'Parent',RadioGroup);
r2T = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.02 0.52 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R2',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.52 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
r2 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.4 0.52 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R2,...
    'BackgroundColor','w',...
    'Callback',['R2=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
xR2Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.6 0.52 0.22 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR2,...
    'BackgroundColor','w',...
    'Callback',['xR2=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
r3T = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.02 0.32 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R3',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.32 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
r3 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.4 0.32 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R3,...
    'BackgroundColor','w',...
    'Callback',['R3=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
xR3Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.6 0.32 0.22 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR3,...
    'BackgroundColor','w',...
    'Callback',['xR3=','get(gco,''Value'');close; Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
    'Parent',RadioGroup);

r4T=uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.02 0.14 0.15 .1],...
    'FontSize',12,...
    'FontAngle','italic',...
    'String','R4',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);

eq = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.2 0.14 0.1 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','=',...
    'BackgroundColor','w',...
    'Parent',RadioGroup);
r4 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.4 0.14 0.2 .1],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',R4,...
    'BackgroundColor','w',...
    'Callback',['R4=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
    'Parent',RadioGroup);
xR4Pop = uicontrol('Style','popupmenu',...
    'Units','normalized',...
    'Position',[0.6 0.14 0.22 .1],...
    'FontSize',10,...
    'FontAngle','italic',...
    'String','Ω|kΩ|MΩ',...
    'Value',xR4,...
    'BackgroundColor','w',...
    'Callback',['xR4=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)'],...
     'Parent',RadioGroup);
........................................Imagine cu circuitul Sumator...............................................................................................................................................................................................................................................................................
uicontrol("Style","pushbutton",...
    "Units","normalized",...
    'Position',[0.01 0.88 0.98 .05],...
    'FontAngle','italic',...
    'FontSize',18,...
    'String','Amplificatorul Sumator',...
    'BackgroundColor','[0.6350 0.0780 0.1840]',...
    'Callback','Imagine_Sumator');
%........................................Semnalele de intrare......................................................................................................................................................................................................................................
in1 = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.10 0.7 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare v1:',...
    'BackgroundColor','#A2142F');
tip1 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.25 0.7 0.09 0.03],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular|Dinte Fier",...
    'Value',Semnal1,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'Callback',['Semnal1=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.34 0.7 0.09 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'String','Vmed [V]');

vMed1 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.43 0.7 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed1,...
    'BackgroundColor','#A2142F',...
    'Callback',['ValMed1=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

if Semnal1 == 2 || Semnal1 == 3 ||Semnal1==4|| Semnal1 ==5
    amplitudinetext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.47 0.7 0.04 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','A[V]');
    amplitudine1 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.51 0.7 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Amplitudine1,...
        'BackgroundColor','#A2142F',...
        'Callback',['Amplitudine1=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

 frecventaltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.55 0.7 0.04 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','F[Hz]');
f1 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.59 0.7 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',frecventa1,...
        'BackgroundColor','#A2142F',...
        'Callback',['frecventa1=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

end

in2 = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.10 0.66 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare v2:',...
    'BackgroundColor','#A2142F');

tip2 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.25 0.66 0.09 0.03],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular|Dinte Fier",...
    'Value',Semnal2,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'Callback',['Semnal2=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.34 0.66 0.09 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'String','Vmed[V]');
vMed2 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.43 0.66 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed2,...
    'BackgroundColor','#A2142F',...
    'Callback',['ValMed2=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

if Semnal2 == 2 || Semnal2 == 3 ||Semnal2==4|| Semnal2 == 5
     amplitudinetext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.47 0.66 0.04 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','A[V]');
     amplitudine2 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.51 0.66 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Amplitudine2,...
        'BackgroundColor','#A2142F',...
        'Callback',['Amplitudine2=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
ftext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.55 0.66 0.06 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','F[Hz]');
 fr2 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.59 0.66 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',frecventa2,...
        'BackgroundColor','#A2142F',...
        'Callback',['frecventa2=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
end
in3 = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.10 0.62 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare v3:',...
    'BackgroundColor','#A2142F');
tip3 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.25 0.62 0.09 0.03],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular|Dinte Fier",...
    'Value',Semnal3,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'Callback',['Semnal3=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.34 0.62 0.09 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'String','Vmed[V]');

vMed3 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.43 0.62 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed3,...
    'BackgroundColor','#A2142F',...
    'Callback',['ValMed3=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
if Semnal3 == 2 || Semnal3 == 3 ||Semnal3==4|| Semnal3 == 5
    ampltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.47 0.62 0.05 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','A[V]');

    ampl3 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.51 0.62 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Amplitudine3,...
        'BackgroundColor','#A2142F',...
        'Callback',['Amplitudine3=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

    fltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.55 0.62 0.06 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','F[Hz]');

    fr3 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.59 0.62 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',frecventa3,...
        'BackgroundColor','#A2142F',...
        'Callback',['frecventa3=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
end

in4= uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.10 0.58 0.15 .03],...
    'FontSize',10,...
    'FontWeight','bold',...
    'String','Semnal de intrare v4:',...
    'BackgroundColor','#A2142F');
tip4 = uicontrol('Style','PopupMenu',...
    'Units','normalized',...
    'Position',[0.25 0.58 0.09 0.03],...
    'String',"Continuu|Sinus|Dreptunghiular|Triunghiular|Dinte Fier",...
    'Value',Semnal4,...
    'FontSize',10,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'Callback',['Semnal4=','get(gco,''Value'');close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

vmedtext = uicontrol('Style','text',...
    'Units','normalized',...
    'Position',[0.34 0.58 0.09 .03],...
    'FontSize',11,...
    'FontAngle','italic',...
    'BackgroundColor','#A2142F',...
    'String','Vmed[V]');

vMed3 = uicontrol("Style","edit",...
    'Units','normalized',...
    'Position',[0.43 0.58 0.04 .03],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String',ValMed4,...
    'BackgroundColor','#A2142F',...
    'Callback',['ValMed4=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
if Semnal4 == 2 || Semnal4 == 3 ||Semnal4==4|| Semnal4 == 5
    ampltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.47 0.58 0.05 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','A[V]');

    ampl4 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.51 0.58 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',Amplitudine4,...
        'BackgroundColor','#A2142F',...
        'Callback',['Amplitudine4=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

    fltext = uicontrol('Style','text',...
        'Units','normalized',...
        'Position',[0.55 0.58 0.06 .03],...
        'FontSize',11,...
        'FontAngle','italic',...
        'BackgroundColor','#A2142F',...
        'String','F[Hz]');

    fr4 = uicontrol("Style","edit",...
        'Units','normalized',...
        'Position',[0.59 0.58 0.04 .03],...
        'FontAngle','italic',...
        'FontSize',11,...
        'String',frecventa4,...
        'BackgroundColor','#A2142F',...
        'Callback',['frecventa4=','str2num(get(gco,''String''));close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);
end
%......................................................Buton Reset.................................................................................................................................................................................................................................................................................................................
uicontrol("Style","pushbutton",...
    "Units","normalized",...
    'Position',[0.01 0.04 0.1 .05],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String','Resetare',...
    'BackgroundColor','#A2142F',...
    'Callback',['frecventa1=50,frecventa2=50,frecventa3=50,frecventa4=50,ValMed1=0,ValMed2=0,ValMed3=0,ValMed4=0,Amplitudine1=0,Amplitudine2=0,Amplitudine3=0,Amplitudine4=0,R1=200,R2=200,R3=200,R4=200,Rn=200,Valimentare=15,Semnal1=2,Semnal2=2,Semnal3=2,Semnal4=2,xR1=1,xR2=1,xR3=1,xR4=1,xRn=1;close;Proiect_interfata_SumatorAO(frecventa1,frecventa2,frecventa3,frecventa4,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)']);

uicontrol("Style","pushbutton",...
    "Units","normalized",...
    'Position',[0.01 0.5 0.65 .05],...
    'FontAngle','italic',...
    'FontSize',11,...
    'String','Calcul: Semnale',...
    'BackgroundColor','#A2142F',...
    'Callback','Grafice_semnale(frecventa1,frecventa2,frecventa3,frecventa4,N,ValMed1,ValMed2,ValMed3,ValMed4,Amplitudine1,Amplitudine2,Amplitudine3,Amplitudine4,R1,R2,R3,R4,Rn,Valimentare,Semnal1,Semnal2,Semnal3,Semnal4,xR1,xR2,xR3,xR4,xRn)');
menu=uimenu('Label', 'Documentatie',...
            'Checked', 'on');
uimenu(menu, 'Label', 'Documentație Sumator AO',...
    'Separator', 'on','Accelerator', 'P',...
    'Callback', 'open(''SumatorAO.pptx'')');

end




